/*
 * Copyright 2016-2019 The Reaktivity Project
 *
 * The Reaktivity Project licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

 scope protocol
 {
    scope codec
    {
        struct Binary
        {
            uint16 length;
            octets[length] bytes;
        }

        struct FixedHeader
        {
            int8 packetType;
            int8 remainingLength;
        }

        struct ProtocolName
        {
            int16 length;
            string name;
        }

        struct ConnectPacket
        {
            protocol::codec::FixedHeader fixedHeader;
            protocol::codec::ProtocolName protocolName;
            uint8 protocolVersion;
            uint8 flags;
            uint16 keepAlive;
            uint16 propertyLength;
            octet[propertyLength] properties = null;
            uint16 clientIdLength;
            string clientId;
            uint16 willPropertiesLength;
            uint32 willDelayInterval;
            uint8 willPayloadFormatIndicator;
            uint32 willMessageExpiryInterval;
            string willContentType;
            string willResponseTopic;
            protocol::codec::Binary correlationInfo;
            /* TODO: user property utf-8 string pair */
            string willTopic = null;
            uint16 willPayloadLength;
            protocol::codec::Binary willPayload;
            unit16 usernameLength;
            string username;
            uint16 passwordLength;
            protocol::codec::Binary password;
        }

        struct ConnackPacket
        {
            protocol::codec::FixedHeader fixedHeader;
            int16 variableHeader;
            int8 propertyLength;
        }
    }
 }
