/*
 * Copyright 2016-2019 The Reaktivity Project
 *
 * The Reaktivity Project licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

 scope protocol
 {
    scope codec
    {
        enum MqttPacketType
        {
            CONNECT,
            CONNACK,
            SUBSCRIBE,
            SUBACK,
            UNSUBSCRIBE,
            UNSUBACK,
            PUBLISH,
            PUBACK,
            PUBREC,
            PUBREL,
            PUBCOMP,
            PINGREQ,
            PINGRESP,
            DISCONNECT
        }

        struct Binary
        {
            uint16 length;
            octets[length] bytes;
        }

        struct MqttPacket
        {
            uint8 packetType;
            uint8 remainingLength;
            octets[remainingLength] packet;
        }

        struct MqttByte
        {
            uint8 value;
        }

        struct MqttTopic
        {
            string topic;
            uint8 options;
        }

        union MqttProperty switch (uint8)
        {
            case 0x11: uint32 sessionExpiry;
            case 0x21: uint16 receiveMaximum;
            case 0x27: uint32 maximumPacketSize;
            case 0x22: uint16 topicAliasMaximum;
            case 0x19: uint8 requestResponseInformation;
            case 0x17: uint8 requestProblemInformation;
            case 0x24: uint8 maximumQoS;
            case 0x25: uint8 retainAvailable;
            case 0x12: string assignedClientId;
            case 0x1F: string reasonString;
            case 0x28: uint8 wildcardSubscriptionAvailable;
            case 0x29: uint8 subscriptionIdsAvailable;
            case 0x2A: uint8 sharedSubscriptionAvailable;
            case 0x13: uint16 serverKeepAlive;
            case 0x1A: string responseInformation;
            case 0x1C: string serverReference;
            case 0x15: string authenticationMethod;
            case 0x16: protocol::codec::Binary authenticationData;
            case 0x01: uint8 payloadFormatIndicator;
        }

        struct MqttConnect
        {
            uint8 packetType;
            uint8 remainingLength;
            string16 protocolName;
            uint8 protocolVersion;
            uint8 flags;
            uint16 keepAlive;
            uint8 propertiesLength;
            string16 clientId;
            octets[propertiesLength] properties;
        }

        struct MqttConnack
        {
            uint8 packetType = 0x20;
            uint8 remainingLength;
            uint8 flags;
            uint8 reasonCode;
            varint32 propertiesLength;
            octets[propertiesLength] properties;
        }

        struct MqttPingReq
        {
            uint8 packetType;
            uint8 remainingLength;
        }

        struct MqttPingResp
        {
            uint8 packetType = 0xd0;
            uint8 remainingLength = 0x00;
        }

        struct MqttSubscribe
        {
            uint8 packetType;
            uint8 remainingLength;
            uint16 packetId;
            varint32 propertiesLength;
            octets[propertiesLength] properties;
            list<protocol::codec::MqttTopic> topics;
        }

        struct MqttSuback
        {
            uint8 packetType = 0x90;
            uint8 remainingLength;
            uint16 packetId;
            octets reasonCodes;
        }

        struct MqttUnsubscribe
        {
            uint8 packetType;
            uint8 remainingLength;
            uint16 packetId;
            varint32 propertiesLength;
            octets[propertiesLength] properties;
            list<string> topics;
        }

        struct MqttUnsuback
        {
            uint8 packetType = 0xa0;
            uint8 remainingLength;
            uint16 packetId;
            octets reasonCodes;
        }

        struct MqttPublish
        {
            uint8 packetType;
            uint8 remainingLength;
            string topic;
            uint16 packetId;
            varint32 propertiesLength;
            octets[propertiesLength] properties;
        }

        struct MqttDisconnect
        {
            uint8 packetType = 0xe0;
            uint8 remainingLength;
            uint8 reasonCode;
            varint32 propertiesLength;
            octets[propertiesLength] properties;
        }
    }
 }
